### ISSUE TITLE
New images for all animals 

### ISSUE THREAD

**Issue by annaingels131** [espinozamaria/animal-project#22]
Crop to a certain size.  
MAKE SURE THEY ARE ROYALTY FREE!!!!!!!!!
https://docs.google.com/document/d/1sDbFR0N7OOuI3rrNAS13mHBv0yvLXRQrQOhipxu3OXw/edit?usp=sharing

**Comment by alexavanhooser** [comment]
-split evenly between alexa/marisol

**Comment by alexavanhooser** [comment]
https://docs.google.com/document/d/1mwLp4C3WuT4CPFhM3Fe8fTsHpcs55mbHgKoapdY5jlI/edit?usp=sharing

**Comment by alexavanhooser** [comment]
If we need to resize images, use [https://pixlr.com/editor/]
