### ISSUE TITLE
Source Component

### ISSUE THREAD

**Issue by annaingels131** [espinozamaria/animal-project#31]
We will need something that cites our sources because we don't want to get in trouble for plagiarism!

**Comment by iam-marixo** [comment]
animalfactguide.com/
awf.org/
en.wikipedia.org/wiki/Endangered_species
en.wikipedia.org/wiki/World_Wide_Fund_for_Nature
kids.nationalgeographic.com/
seaworld.org/
shutterstock.com/
unsplash.com/
worldwildlife.org
