### ISSUE TITLE
Footer - Add link navigation

### ISSUE THREAD

**Issue by espinozamaria** [espinozamaria/animal-project#9]
Perhaps the links at bottom of page can be modified so that it will travel to that website, WWF, Github, etc.
Also, maybe instead of px for the button, vw/vh can be used in order to have the webpage be stable and not require scrolling

**Comment by annaingels131** [comment]
Delete leaderboard and link media. 
Add donation button

**Comment by alexavanhooser** [comment]
-link to WWF

**Comment by alexavanhooser** [comment]
change color: (orange from the Hop)
-change link colors

**Comment by alexavanhooser** [comment]
-change footer circle to orange
-try to get rid of the white box around the circle
-grey background to orange
-text white
